server:
  port: 8090

spring:
  application:
    name: milkstgopep1
  jpa:
    show-sql: true
    hibernate:
      dialect: MySQL8Dialect
      ddl-auto: create
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbname: bdproyecto
    url: jdbc:mysql://localhost:3306/bdproyecto
    username: root
    password: password
