apiVersion: v1
kind: Service
metadata:
  name: planilla-service
  labels:
    app: planilla-service
spec:
  selector:
    app: planilla-deployment
  ports:
    - protocol: TCP
      port: 8084
      targetPort: 8084
  type: LoadBalancer